version: '3'
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  logistics-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongodb
